name: Question or Support
description: Ask a question about using or customizing
title: '[Question]: '
labels: ['question']
assignees: []
body:
  - type: markdown
    attributes:
      value: Please provide as much context as possible to ensure an effective response.

  - type: checkboxes
    id: terms
    attributes:
      label: Preflight Checklist
      description: Please ensure these steps have been completed before asking
      options:
        - label: I have searched existing issues and discussions for similar questions
          required: true
        - label: I have checked the documentation and README
          required: true
        - label: I have tried the suggested build or Sass configuration steps (if applicable)
          required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Be as specific as possible about what you're trying to accomplish (e.g., variable overrides, build setup, or custom components)
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you trying to achieve?
      placeholder: Describe your use case or what you’re building with this project
    validations:
      required: true

  - type: textarea
    id: attempted-solutions
    attributes:
      label: What Have You Tried?
      description: What approaches or Sass configurations have you already attempted?
      placeholder: List steps or snippets you've tried

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: Please provide your environment information
      placeholder: |
        - OS: [e.g. macOS 14.0, Windows 11, Ubuntu 22.04]
        - Node.js version: [e.g. 22.12.0]
        - npm version: [e.g. 10.5.0]
        - Browser (if applicable): [e.g. Chrome 120, Safari 17]
      render: markdown

  - type: textarea
    id: code-example
    attributes:
      label: Code Example (if applicable)
      description: Share any relevant Sass or configuration code
      placeholder: Paste your relevant `_variables.scss`, build config, or CSS output
      render: shell

  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What category does your question fall into?
      options:
        - Setup and installation
        - Sass compilation
        - Variable customization
        - Build or output optimization
        - CSS organization
        - Utility classes or mixins
        - Theming and color systems
        - Browser support or compatibility
        - Other
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context that might be helpful
      placeholder: Screenshots, links to code examples, or related documentation